"""add_composite_indexes_to_memberships_and_relationships

Revision ID: 996fe3ad69c3
Revises: 92f6e9468cb4
Create Date: 2025-10-01 08:09:07.468932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996fe3ad69c3'
down_revision = '92f6e9468cb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_memberships_tree_id'), 'memberships', ['tree_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index('ix_memberships_user_tree', 'memberships', ['user_id', 'tree_id'], unique=True)
    op.create_index('ix_relationships_members', 'relationships', ['a_member_id', 'b_member_id'], unique=False)
    op.create_index('ix_relationships_tree_type', 'relationships', ['tree_id', 'type'], unique=False)
    op.create_index(op.f('ix_relationships_type'), 'relationships', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_type'), table_name='relationships')
    op.drop_index('ix_relationships_tree_type', table_name='relationships')
    op.drop_index('ix_relationships_members', table_name='relationships')
    op.drop_index('ix_memberships_user_tree', table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tree_id'), table_name='memberships')
    # ### end Alembic commands ###
